
#define HMI_START_END_CHAR  126 // 0x7E

#define MAX_PACKET_SIZE_FROM_HMI 95

//msg type
#define HMI_SCREEN_DATA 0x01
#define HMI_BG_DATA 0x02
//Screens
#define HMI_IDLE_SCREEN 0x01
#define HMI_RUN_SCREEN 0x02
#define HMI_STOP_SCREEN 0x03
// Information
#define HMI_SETTINGS_INFO 0x04
#define HMI_SETTINGS_PACKET_LEN_RF 23 //without the /r in the end
#define HMI_DIAG_RESULTS 0x05 
//DIAG_TEST_Results

#define HMI_DIAG_TEST_SUCCESSFUL 0x98
#define HMI_DIAG_TEST_FAIL 0x97
#define HMI_DIAG_TEST_MOTORERROR 0x96
#define HMI_DIAG_TEST_LIFT_W_OLD_DOFF 0x95

//SubScreens 
#define HMI_RUN_NORMAL 0x01
#define HMI_RUN_RAMPUP 0x02
#define HMI_RUN_PIECING 0x03
#define HMI_RUN_HOMING 0x04
#define HMI_RUN_PACKET_LENGTH_RF 17 //BUG:this can be anything but the hex value mustbe able to be interpreted by the app as a int
#define HMI_STOP_PAUSE 0x11 
#define HMI_STOP_HALT 0x12
#define HMI_STOP_PACKET_LENGTH 19
#define HMI_END_DIAG_TEST 0x98


//Senders
#define MACHINE_TO_HMI 0x01
#define HMI_TO_MACHINE 0x02


//ATTRIBUTE CODES
//1. FOR RUN SCREENS
#define HMI_RF_PRODUCTION_RUN 0x05
#define HMI_RF_SPINDLESPEED 0x06
#define HMI_RD_LEFT_DOFFPERCENT 0x07
#define HMI_RD_RIGHT_DOFFPERCENT 0x08

//2. for STOP Screens
#define HMI_STOP_REASON_CODE  0x01
#define HMI_MOTOR_FAULT_CODE 0x02
#define HMI_ERROR_VAL_CODE 0x03
#define HMI_USER_PAUSE 0x99


//3.BLOW CARD MOTORS and error reasons.
//Same as RPI.

//4. DIAG CODES // NOT USED
#define HMI_DIAG_TEST_CODE 0x01
//attibutes
#define HMI_DIAG_CLOSED_LOOP  0x01
#define HMI_DIAG_OPEN_LOOP  0x02

#define HMI_DIAG_END_OF_TEST_CODE 0x0A //RETURN

//SETTINGS
#define HMI_RF_ALL_SETTING_CODE 0x80
#define HMI_RF_ALL_SETTINGS_PKT_LEN 28

// RETURN MSGS FROM HMI TO MACHINE
#define FROM_HMI_IM_PAIRED 0x99
#define IM_PAIRED_PACKET_LENGTH 26  // including the /r
#define FROM_HMI_DISABLE_MACHINE_START 0x03
#define FROM_HMI_ENABLE_MACHINE_START 0x02
#define FROM_HMI_RTF_UPDATE 0x07
#define FROM_HMI_IN_SETTINGS_CHANGE 0x01
#define FROM_HMI_IN_DIAGNOSTICS_SET 0x02
#define FROM_HMI_BACK_TO_IDLE 0x00
#define FROM_HMI_UPDATED_SETTINGS 0x06
#define FROM_HMI_NEW_DOFF 0x06 //this comes from thehmi
#define SIGNAL_NEW_DOFF  0x08 // this signals something has come
#define RTF_ADD 0x02
#define RTF_SUBTRACT 0x03

#define FROM_HMI_CHANGE_PROCESS_PARAMS 0x04
#define FROM_HMI_CHANGE_HW_PARAMS 0x03 //unused
#define FROM_HMI_DIAGNOSTIC_TEST 0x05

#define BAD_HMI_MSG 0x77
//INTERNALLY DEFINED MSGS

#define FROM_MC_ACK_UPDATED_SETTINGS 0x99
#define RESET_DOFF 0x94
#define FROM_MC_ACK_PKT_LEN 11
#define FROM_DIAG_UPDATED_TEST_DETAILS 0x10
#define RUN_DIAG_TEST 0x12
#define ADD_TO_RTF 0x09
#define SUBTRACT_FROM_RTF 0x0A
#define HOMING_RTF_CHANGE 0x0B

//MOTOR CODES FOR HMI ONLY
#define HMI_RD_FRONTROLLER_RIGHT 0x46
#define HMI_RD_BACKROLLER_FRONT 0x47
#define HMI_RD_FRONTROLLER_LEFT 0x48
#define HMI_RD_BACKROLLER_BACK 0x49
#define HMI_RD_LIFT_RIGHT 0x4A
#define HMI_RD_LIFT_LEFT 0x4B
#define HMI_RD_SPINDLE 0x4C


